function Graficar_SCL_MS_Juntos(SCL, frecuencia, escala)
% Grafica los sistemas coordenados locales del miembro superior
%
% Entradas:
%   SCL - estructura con sistemas coordenados locales
%   frecuencia - cada cuántos frames graficar (default: 10)
%   escala - factor de escala para los vectores (default: 0.1)

    if nargin < 2
        frecuencia = 10;
    end
    
    if nargin < 3
        escala = 0.1;
    end
    
    % Índices a graficar
    n_frames = size(SCL.Pelvis.Origen, 1);
    idx = 1:frecuencia:n_frames;
    
    figure;
    hold on;
    
    % PELVIS
    origenes = SCL.Pelvis.Origen(idx,:);
    quiver3(origenes(:,1), origenes(:,2), origenes(:,3), ...
            SCL.Pelvis.u(idx,1)*escala, SCL.Pelvis.u(idx,2)*escala, SCL.Pelvis.u(idx,3)*escala, ...
            'r', 'LineWidth', 2, 'MaxHeadSize', 0.5, 'AutoScale', 'off');
    quiver3(origenes(:,1), origenes(:,2), origenes(:,3), ...
            SCL.Pelvis.v(idx,1)*escala, SCL.Pelvis.v(idx,2)*escala, SCL.Pelvis.v(idx,3)*escala, ...
            'g', 'LineWidth', 2, 'MaxHeadSize', 0.5, 'AutoScale', 'off');
    quiver3(origenes(:,1), origenes(:,2), origenes(:,3), ...
            SCL.Pelvis.w(idx,1)*escala, SCL.Pelvis.w(idx,2)*escala, SCL.Pelvis.w(idx,3)*escala, ...
            'b', 'LineWidth', 2, 'MaxHeadSize', 0.5, 'AutoScale', 'off');
    
    % TÓRAX
    origenes = SCL.Torax.Origen(idx,:);
    quiver3(origenes(:,1), origenes(:,2), origenes(:,3), ...
            SCL.Torax.u(idx,1)*escala, SCL.Torax.u(idx,2)*escala, SCL.Torax.u(idx,3)*escala, ...
            'r', 'LineWidth', 2, 'MaxHeadSize', 0.5, 'AutoScale', 'off');
    quiver3(origenes(:,1), origenes(:,2), origenes(:,3), ...
            SCL.Torax.v(idx,1)*escala, SCL.Torax.v(idx,2)*escala, SCL.Torax.v(idx,3)*escala, ...
            'g', 'LineWidth', 2, 'MaxHeadSize', 0.5, 'AutoScale', 'off');
    quiver3(origenes(:,1), origenes(:,2), origenes(:,3), ...
            SCL.Torax.w(idx,1)*escala, SCL.Torax.w(idx,2)*escala, SCL.Torax.w(idx,3)*escala, ...
            'b', 'LineWidth', 2, 'MaxHeadSize', 0.5, 'AutoScale', 'off');
    
    % HÚMERO DERECHO
    origenes = SCL.Humero_R.Origen(idx,:);
    quiver3(origenes(:,1), origenes(:,2), origenes(:,3), ...
            SCL.Humero_R.u(idx,1)*escala, SCL.Humero_R.u(idx,2)*escala, SCL.Humero_R.u(idx,3)*escala, ...
            'r', 'LineWidth', 2, 'MaxHeadSize', 0.5, 'AutoScale', 'off');
    quiver3(origenes(:,1), origenes(:,2), origenes(:,3), ...
            SCL.Humero_R.v(idx,1)*escala, SCL.Humero_R.v(idx,2)*escala, SCL.Humero_R.v(idx,3)*escala, ...
            'g', 'LineWidth', 2, 'MaxHeadSize', 0.5, 'AutoScale', 'off');
    quiver3(origenes(:,1), origenes(:,2), origenes(:,3), ...
            SCL.Humero_R.w(idx,1)*escala, SCL.Humero_R.w(idx,2)*escala, SCL.Humero_R.w(idx,3)*escala, ...
            'b', 'LineWidth', 2, 'MaxHeadSize', 0.5, 'AutoScale', 'off');
    
    % HÚMERO IZQUIERDO
    origenes = SCL.Humero_L.Origen(idx,:);
    quiver3(origenes(:,1), origenes(:,2), origenes(:,3), ...
            SCL.Humero_L.u(idx,1)*escala, SCL.Humero_L.u(idx,2)*escala, SCL.Humero_L.u(idx,3)*escala, ...
            'r', 'LineWidth', 2, 'MaxHeadSize', 0.5, 'AutoScale', 'off');
    quiver3(origenes(:,1), origenes(:,2), origenes(:,3), ...
            SCL.Humero_L.v(idx,1)*escala, SCL.Humero_L.v(idx,2)*escala, SCL.Humero_L.v(idx,3)*escala, ...
            'g', 'LineWidth', 2, 'MaxHeadSize', 0.5, 'AutoScale', 'off');
    quiver3(origenes(:,1), origenes(:,2), origenes(:,3), ...
            SCL.Humero_L.w(idx,1)*escala, SCL.Humero_L.w(idx,2)*escala, SCL.Humero_L.w(idx,3)*escala, ...
            'b', 'LineWidth', 2, 'MaxHeadSize', 0.5, 'AutoScale', 'off');
    
    % ANTEBRAZO DERECHO
    origenes = SCL.Antebrazo_R.Origen(idx,:);
    quiver3(origenes(:,1), origenes(:,2), origenes(:,3), ...
            SCL.Antebrazo_R.u(idx,1)*escala, SCL.Antebrazo_R.u(idx,2)*escala, SCL.Antebrazo_R.u(idx,3)*escala, ...
            'r', 'LineWidth', 2, 'MaxHeadSize', 0.5, 'AutoScale', 'off');
    quiver3(origenes(:,1), origenes(:,2), origenes(:,3), ...
            SCL.Antebrazo_R.v(idx,1)*escala, SCL.Antebrazo_R.v(idx,2)*escala, SCL.Antebrazo_R.v(idx,3)*escala, ...
            'g', 'LineWidth', 2, 'MaxHeadSize', 0.5, 'AutoScale', 'off');
    quiver3(origenes(:,1), origenes(:,2), origenes(:,3), ...
            SCL.Antebrazo_R.w(idx,1)*escala, SCL.Antebrazo_R.w(idx,2)*escala, SCL.Antebrazo_R.w(idx,3)*escala, ...
            'b', 'LineWidth', 2, 'MaxHeadSize', 0.5, 'AutoScale', 'off');
    
    % ANTEBRAZO IZQUIERDO
    origenes = SCL.Antebrazo_L.Origen(idx,:);
    quiver3(origenes(:,1), origenes(:,2), origenes(:,3), ...
            SCL.Antebrazo_L.u(idx,1)*escala, SCL.Antebrazo_L.u(idx,2)*escala, SCL.Antebrazo_L.u(idx,3)*escala, ...
            'r', 'LineWidth', 2, 'MaxHeadSize', 0.5, 'AutoScale', 'off');
    quiver3(origenes(:,1), origenes(:,2), origenes(:,3), ...
            SCL.Antebrazo_L.v(idx,1)*escala, SCL.Antebrazo_L.v(idx,2)*escala, SCL.Antebrazo_L.v(idx,3)*escala, ...
            'g', 'LineWidth', 2, 'MaxHeadSize', 0.5, 'AutoScale', 'off');
    quiver3(origenes(:,1), origenes(:,2), origenes(:,3), ...
            SCL.Antebrazo_L.w(idx,1)*escala, SCL.Antebrazo_L.w(idx,2)*escala, SCL.Antebrazo_L.w(idx,3)*escala, ...
            'b', 'LineWidth', 2, 'MaxHeadSize', 0.5, 'AutoScale', 'off');
    
    % MANO DERECHA
    origenes = SCL.Mano_R.Origen(idx,:);
    quiver3(origenes(:,1), origenes(:,2), origenes(:,3), ...
            SCL.Mano_R.u(idx,1)*escala, SCL.Mano_R.u(idx,2)*escala, SCL.Mano_R.u(idx,3)*escala, ...
            'r', 'LineWidth', 2, 'MaxHeadSize', 0.5, 'AutoScale', 'off');
    quiver3(origenes(:,1), origenes(:,2), origenes(:,3), ...
            SCL.Mano_R.v(idx,1)*escala, SCL.Mano_R.v(idx,2)*escala, SCL.Mano_R.v(idx,3)*escala, ...
            'g', 'LineWidth', 2, 'MaxHeadSize', 0.5, 'AutoScale', 'off');
    quiver3(origenes(:,1), origenes(:,2), origenes(:,3), ...
            SCL.Mano_R.w(idx,1)*escala, SCL.Mano_R.w(idx,2)*escala, SCL.Mano_R.w(idx,3)*escala, ...
            'b', 'LineWidth', 2, 'MaxHeadSize', 0.5, 'AutoScale', 'off');
    
    % MANO IZQUIERDA
    origenes = SCL.Mano_L.Origen(idx,:);
    quiver3(origenes(:,1), origenes(:,2), origenes(:,3), ...
            SCL.Mano_L.u(idx,1)*escala, SCL.Mano_L.u(idx,2)*escala, SCL.Mano_L.u(idx,3)*escala, ...
            'r', 'LineWidth', 2, 'MaxHeadSize', 0.5, 'AutoScale', 'off');
    quiver3(origenes(:,1), origenes(:,2), origenes(:,3), ...
            SCL.Mano_L.v(idx,1)*escala, SCL.Mano_L.v(idx,2)*escala, SCL.Mano_L.v(idx,3)*escala, ...
            'g', 'LineWidth', 2, 'MaxHeadSize', 0.5, 'AutoScale', 'off');
    quiver3(origenes(:,1), origenes(:,2), origenes(:,3), ...
            SCL.Mano_L.w(idx,1)*escala, SCL.Mano_L.w(idx,2)*escala, SCL.Mano_L.w(idx,3)*escala, ...
            'b', 'LineWidth', 2, 'MaxHeadSize', 0.5, 'AutoScale', 'off');
    
    hold off;
    
    xlabel('X [m]');
    ylabel('Y [m]');
    zlabel('Z [m]');
    title('Sistemas Coordenados Locales - Miembro Superior');
    grid on;
    axis equal;
    axis tight;
    view(3);
    rotate3d on;
end