function Graficar_SCL_MS(SCL)
% Grafica los sistemas coordenados locales del miembro superior
%
% Entradas:
%   mar - estructura con marcadores
%   SCL - estructura con sistemas coordenados locales

    figure;
    
    % SUBPLOT 1: PELVIS
    subplot(2, 4, 1);
    origenes = SCL.Pelvis.Origen;
    vectores.u = SCL.Pelvis.u;
    vectores.v = SCL.Pelvis.v;
    vectores.w = SCL.Pelvis.w;
    config = struct( ...
        'ColorU', [1 0 0], ...
        'ColorV', [0 1 0], ...
        'ColorW', [0 0 1], ...
        'EtiquetaO', 'Origen (sacrum)', ...
        'EtiquetaU', 'X\_P', ...
        'EtiquetaV', 'Y\_P', ...
        'EtiquetaW', 'Z\_P', ...
        'Titulo', 'Pelvis', ...
        'Frecuencia', 20, ...
        'MostrarOrigen', true);
    hold on;
    graficar_vectores(origenes, vectores, config);
    legend off;
    hold off;
    
    % SUBPLOT 2: TÓRAX
    subplot(2, 4, 2);
    origenes = SCL.Torax.Origen;
    vectores.u = SCL.Torax.u;
    vectores.v = SCL.Torax.v;
    vectores.w = SCL.Torax.w;
    config = struct( ...
        'ColorU', [1 0 0], ...
        'ColorV', [0 1 0], ...
        'ColorW', [0 0 1], ...
        'EtiquetaO', 'Origen (IJ)', ...
        'EtiquetaU', 'X\_T', ...
        'EtiquetaV', 'Y\_T', ...
        'EtiquetaW', 'Z\_T', ...
        'Titulo', 'Tórax', ...
        'Frecuencia', 20, ...
        'MostrarOrigen', true);
    hold on;
    graficar_vectores(origenes, vectores, config);
    legend off;
    hold off;
    
    % SUBPLOT 3: HÚMERO DERECHO
    subplot(2, 4, 3);
    origenes = SCL.Humero_R.Origen;
    vectores.u = SCL.Humero_R.u;
    vectores.v = SCL.Humero_R.v;
    vectores.w = SCL.Humero_R.w;
    config = struct( ...
        'ColorU', [1 0 0], ...
        'ColorV', [0 1 0], ...
        'ColorW', [0 0 1], ...
        'EtiquetaO', 'Origen (GH\_R)', ...
        'EtiquetaU', 'X\_H2\_R', ...
        'EtiquetaV', 'Y\_H2\_R', ...
        'EtiquetaW', 'Z\_H2\_R', ...
        'Titulo', 'Húmero Derecho', ...
        'Frecuencia', 20, ...
        'MostrarOrigen', true);
    hold on;
    graficar_vectores(origenes, vectores, config);
    legend off;
    hold off;
    
    % SUBPLOT 4: HÚMERO IZQUIERDO
    subplot(2, 4, 4);
    origenes = SCL.Humero_L.Origen;
    vectores.u = SCL.Humero_L.u;
    vectores.v = SCL.Humero_L.v;
    vectores.w = SCL.Humero_L.w;
    config = struct( ...
        'ColorU', [1 0 0], ...
        'ColorV', [0 1 0], ...
        'ColorW', [0 0 1], ...
        'EtiquetaO', 'Origen (GH\_L)', ...
        'EtiquetaU', 'X\_H2\_L', ...
        'EtiquetaV', 'Y\_H2\_L', ...
        'EtiquetaW', 'Z\_H2\_L', ...
        'Titulo', 'Húmero Izquierdo', ...
        'Frecuencia', 20, ...
        'MostrarOrigen', true);
    hold on;
    graficar_vectores(origenes, vectores, config);
    legend off;
    hold off;
    
    % SUBPLOT 5: ANTEBRAZO DERECHO
    subplot(2, 4, 5);
    origenes = SCL.Antebrazo_R.Origen;
    vectores.u = SCL.Antebrazo_R.u;
    vectores.v = SCL.Antebrazo_R.v;
    vectores.w = SCL.Antebrazo_R.w;
    config = struct( ...
        'ColorU', [1 0 0], ...
        'ColorV', [0 1 0], ...
        'ColorW', [0 0 1], ...
        'EtiquetaO', 'Origen (US\_R)', ...
        'EtiquetaU', 'X\_A\_R', ...
        'EtiquetaV', 'Y\_A\_R', ...
        'EtiquetaW', 'Z\_A\_R', ...
        'Titulo', 'Antebrazo Derecho', ...
        'Frecuencia', 20, ...
        'MostrarOrigen', true);
    hold on;
    graficar_vectores(origenes, vectores, config);
    legend off;
    hold off;
    
    % SUBPLOT 6: ANTEBRAZO IZQUIERDO
    subplot(2, 4, 6);
    origenes = SCL.Antebrazo_L.Origen;
    vectores.u = SCL.Antebrazo_L.u;
    vectores.v = SCL.Antebrazo_L.v;
    vectores.w = SCL.Antebrazo_L.w;
    config = struct( ...
        'ColorU', [1 0 0], ...
        'ColorV', [0 1 0], ...
        'ColorW', [0 0 1], ...
        'EtiquetaO', 'Origen (US\_L)', ...
        'EtiquetaU', 'X\_A\_L', ...
        'EtiquetaV', 'Y\_A\_L', ...
        'EtiquetaW', 'Z\_A\_L', ...
        'Titulo', 'Antebrazo Izquierdo', ...
        'Frecuencia', 20, ...
        'MostrarOrigen', true);
    hold on;
    graficar_vectores(origenes, vectores, config);
    legend off;
    hold off;
    
    % SUBPLOT 7: MANO DERECHA
    subplot(2, 4, 7);
    origenes = SCL.Mano_R.Origen;
    vectores.u = SCL.Mano_R.u;
    vectores.v = SCL.Mano_R.v;
    vectores.w = SCL.Mano_R.w;
    config = struct( ...
        'ColorU', [1 0 0], ...
        'ColorV', [0 1 0], ...
        'ColorW', [0 0 1], ...
        'EtiquetaO', 'Origen (Muñeca\_R)', ...
        'EtiquetaU', 'X\_M\_R', ...
        'EtiquetaV', 'Y\_M\_R', ...
        'EtiquetaW', 'Z\_M\_R', ...
        'Titulo', 'Mano Derecha', ...
        'Frecuencia', 20, ...
        'MostrarOrigen', true);
    hold on;
    graficar_vectores(origenes, vectores, config);
    legend off;
    hold off;
    
    % SUBPLOT 8: MANO IZQUIERDA
    subplot(2, 4, 8);
    origenes = SCL.Mano_L.Origen;
    vectores.u = SCL.Mano_L.u;
    vectores.v = SCL.Mano_L.v;
    vectores.w = SCL.Mano_L.w;
    config = struct( ...
        'ColorU', [1 0 0], ...
        'ColorV', [0 1 0], ...
        'ColorW', [0 0 1], ...
        'EtiquetaO', 'Origen (Muñeca\_L)', ...
        'EtiquetaU', 'X\_M\_L', ...
        'EtiquetaV', 'Y\_M\_L', ...
        'EtiquetaW', 'Z\_M\_L', ...
        'Titulo', 'Mano Izquierda', ...
        'Frecuencia', 20, ...
        'MostrarOrigen', true);
    hold on;
    graficar_vectores(origenes, vectores, config);
    legend off;
    hold off;
    
    sgtitle('Sistemas Coordenados Locales - Miembro Superior');
end